controller_list:
  - name: fake_mico_arm_controller
    joints:
      - m1n6s300_joint_1
      - m1n6s300_joint_2
      - m1n6s300_joint_3
      - m1n6s300_joint_4
      - m1n6s300_joint_5
      - m1n6s300_joint_6
  - name: fake_mico_gripper_controller
    joints:
      - m1n6s300_joint_finger_1
      - m1n6s300_joint_finger_2
      - m1n6s300_joint_finger_3