# Set this parameter to use a specific arm on your system    --> 
# serial_number: PJ00000001030703130

# Joint speed limit for joints 1, 2, 3
jointSpeedLimitParameter1: 10

# Joint speed limit for joints 4, 5, 6
jointSpeedLimitParameter2: 20

# payload: [COM COMx COMy COMz]
payload: [0, 0, 0, 0]

# connection type
connection_type: ethernet #USB

# Ethernet connection parameters
ethernet: {
  local_machine_IP: 192.168.100.21,
  subnet_mask: 255.255.255.0,
  local_cmd_port: 25000,
  local_broadcast_port: 25025
}

#Torque control parameters
#Do not change these parameters unless you want to change torque control behavior
torque_parameters: {
    # if torque min/max sepecified, all min/max values need to be specified
    # torque_min: [1, 0, 0, 0, 0, 0, 0],
    # torque_max: [50, 0, 0, 0, 0, 0, 0],
    # Decides velocity threshold at which robot switches torque to position control (between 0 and 1)
    # safety_factor: 1
}
