# Set this parameter to use a specific arm on your system    --> 
# serial_number: PJ00000001030703130

# Joint speed limit for joints 1, 2, 3
jointSpeedLimitParameter1: 20

# Joint speed limit for joints 4, 5, 6
jointSpeedLimitParameter2: 20
