kinova:
  j2n6s300_joint_1_position_controller:
    joint: j2n6s300_joint_1
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  j2n6s300_joint_2_position_controller:
    joint: j2n6s300_joint_2
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  j2n6s300_joint_3_position_controller:
    joint: j2n6s300_joint_3
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  j2n6s300_joint_4_position_controller:
    joint: j2n6s300_joint_4
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  j2n6s300_joint_5_position_controller:
    joint: j2n6s300_joint_5
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  j2n6s300_joint_6_position_controller:
    joint: j2n6s300_joint_6
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  joint_state_controller:
    publish_rate: 50
    type: joint_state_controller/JointStateController
