kinova:
  joint_state_controller:
    publish_rate: 50
    type: joint_state_controller/JointStateController
  m1n6s200_joint_1_position_controller:
    joint: m1n6s200_joint_1
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  m1n6s200_joint_2_position_controller:
    joint: m1n6s200_joint_2
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  m1n6s200_joint_3_position_controller:
    joint: m1n6s200_joint_3
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  m1n6s200_joint_4_position_controller:
    joint: m1n6s200_joint_4
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  m1n6s200_joint_5_position_controller:
    joint: m1n6s200_joint_5
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  m1n6s200_joint_6_position_controller:
    joint: m1n6s200_joint_6
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  m1n6s200_joint_finger_1_position_controller:
    joint: m1n6s200_joint_finger_1
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
  m1n6s200_joint_finger_2_position_controller:
    joint: m1n6s200_joint_finger_2
    pid:
      d: 10.0
      i: 0.01
      p: 100.0
    type: effort_controllers/JointPositionController
